resources:
  containers:
  - container: arm64v8-test-container
    image: electron.azurecr.io/build:arm64v8-4cec2c5ab66765caa724e37bae2bffb9b29722a5
    options: --shm-size 128m

jobs:
- job: Test_Arm64
  container: arm64v8-test-container
  displayName: Test Arm64 on Arm64 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
